Updated README to specify that this is a fork
CCI-MOC/virtualbmc pull request #1
Opened 2023-05-09 15:52 UTC by tzumainn

2023-05-10 16:33 UTC, samuel-zuk commented on README.rst
>  Supported IPMI commands
I think in the spirit of things, you might want to add a disclaimer that this is in development, experimental, or something to that effect and/or specify which IPMI functions are supported by the tool.

2023-05-10 16:36 UTC, samuel-zuk requested changes
Looks good! It might be a good idea to revise the 'supported IPMI commands' section to reflect the changes we make/intend to make to the code, but other than that this is great.

2023-05-11 13:11 UTC, tzumainn commented on README.rst
>  Supported IPMI commands
Fair enough! I've added "development" in the summary at the top. As far as I'm aware, all the IPMI commands here should work.

2023-05-11 13:12 UTC, tzumainn commented
Change made - let me know what you think!

2023-05-11 21:51 UTC, samuel-zuk approved these changes
Looks good to me!

2023-05-11 21:51 UTC, samuel-zuk commented on README.rst
>  Supported IPMI commands
Ah, okay. Sounds good!

2023-05-11 22:00 UTC, merged